/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Item;
import model.Livro;
import model.Venda;

public class FormVenda extends javax.swing.JFrame {

    Venda venda = null;
    Cliente cliente = null;
    Livro livro = null;
    DefaultTableModel modelo  = null;
    float soma = 0;
    
    public FormVenda() {
        initComponents();
        venda = new Venda();
        modelo = (DefaultTableModel) tbLivros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbVenda = new javax.swing.JLabel();
        lbNumeroVenda = new javax.swing.JLabel();
        lbDataVenda = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        tfCPF = new javax.swing.JFormattedTextField();
        btBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeCliente = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbEnderecoCompleto = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbEmailContato = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        tfCodigoLivro = new javax.swing.JTextField();
        btBuscarItem = new javax.swing.JButton();
        lbTi = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbEd = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbValorUnitario = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        btIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivros = new javax.swing.JTable();
        btRemoverItem = new javax.swing.JButton();
        lbValorT = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        btFecharVenda = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar uma Venda");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbVenda.setText("Venda N°:");
        lbVenda.setName("lbVenda"); // NOI18N

        lbNumeroVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNumeroVenda.setForeground(new java.awt.Color(0, 102, 0));
        lbNumeroVenda.setName("lbNumeroVenda"); // NOI18N

        lbDataVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDataVenda.setForeground(new java.awt.Color(0, 0, 153));
        lbDataVenda.setName("lbDataVenda"); // NOI18N

        lbData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbData.setText("Data da Venda:");
        lbData.setName("lbData"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lbVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNumeroVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(lbData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataVenda)
                .addGap(105, 105, 105))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVenda)
                    .addComponent(lbNumeroVenda)
                    .addComponent(lbData)
                    .addComponent(lbDataVenda))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lbCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCPF.setText("CPF:");
        lbCPF.setName("lbCPF"); // NOI18N

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF.setName("tfCPF"); // NOI18N

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setName("btBuscar"); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbNome.setText("Nome do Cliente:");
        lbNome.setName("lbNome"); // NOI18N

        lbNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNomeCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbNomeCliente.setName("lbNomeCliente"); // NOI18N

        lbEndereco.setText("Endereço Completo:");
        lbEndereco.setName("lbEndereco"); // NOI18N

        lbEnderecoCompleto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEnderecoCompleto.setName("lbEnderecoCompleto"); // NOI18N

        lbTel.setText("Telefone:");
        lbTel.setName("lbTel"); // NOI18N

        lbTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTelefone.setName("lbTelefone"); // NOI18N

        lbEmail.setText("E-mail de contato:");
        lbEmail.setName("lbEmail"); // NOI18N

        lbEmailContato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEmailContato.setName("lbEmailContato"); // NOI18N

        btConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.setEnabled(false);
        btConfirmar.setName("btConfirmar"); // NOI18N
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEndereco)
                            .addComponent(lbEnderecoCompleto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTel)
                            .addComponent(lbTelefone))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbEmailContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfirmar)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(126, 126, 126))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbEndereco)
                    .addComponent(lbTel)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente)
                    .addComponent(lbEnderecoCompleto)
                    .addComponent(lbTelefone)
                    .addComponent(lbEmailContato)
                    .addComponent(btConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Livros a escolher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCodigo.setText("Código Livro:");
        lbCodigo.setName("lbCodigo"); // NOI18N

        tfCodigoLivro.setEnabled(false);
        tfCodigoLivro.setName("tfCodigoLivro"); // NOI18N

        btBuscarItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscarItem.setText("Buscar Item");
        btBuscarItem.setEnabled(false);
        btBuscarItem.setName("btBuscarItem"); // NOI18N
        btBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarItemActionPerformed(evt);
            }
        });

        lbTi.setText("Título:");
        lbTi.setName("lbTi"); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTitulo.setName("lbTitulo"); // NOI18N

        lbEd.setText("Editora:");
        lbEd.setName("lbEd"); // NOI18N

        lbEditora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEditora.setName("lbEditora"); // NOI18N

        lbValor.setText("Valor unitário:");
        lbValor.setName("lbValor"); // NOI18N

        lbValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorUnitario.setForeground(new java.awt.Color(0, 0, 204));
        lbValorUnitario.setName("lbValorUnitario"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btBuscarItem))
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addComponent(lbTi))
                .addGap(145, 145, 145)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEd)
                    .addComponent(lbEditora))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorUnitario)
                    .addComponent(lbValor))
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEd)
                            .addComponent(lbValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTitulo)
                            .addComponent(lbEditora)
                            .addComponent(lbValorUnitario)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(lbTi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarItem))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbQuantidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbQuantidade.setText("Quantidade:");
        lbQuantidade.setName("lbQuantidade"); // NOI18N

        tfQuantidade.setEnabled(false);
        tfQuantidade.setName("tfQuantidade"); // NOI18N

        btIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setEnabled(false);
        btIncluir.setName("btIncluir"); // NOI18N
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        tbLivros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLivros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbLivros.setName("tbLivros"); // NOI18N
        tbLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbLivros);
        if (tbLivros.getColumnModel().getColumnCount() > 0) {
            tbLivros.getColumnModel().getColumn(0).setResizable(false);
            tbLivros.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbLivros.getColumnModel().getColumn(1).setResizable(false);
            tbLivros.getColumnModel().getColumn(1).setPreferredWidth(450);
            tbLivros.getColumnModel().getColumn(2).setResizable(false);
            tbLivros.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbLivros.getColumnModel().getColumn(3).setResizable(false);
            tbLivros.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbLivros.getColumnModel().getColumn(4).setResizable(false);
            tbLivros.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        btRemoverItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRemoverItem.setText("Remover Item");
        btRemoverItem.setEnabled(false);
        btRemoverItem.setName("btRemoverItem"); // NOI18N
        btRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverItemActionPerformed(evt);
            }
        });

        lbValorT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorT.setText("Valor Total:");
        lbValorT.setName("lbValorT"); // NOI18N

        lbValorTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(255, 51, 0));
        lbValorTotal.setText("R$ 0.00");
        lbValorTotal.setName("lbValorTotal"); // NOI18N

        btFecharVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFecharVenda.setText("Fechar Venda");
        btFecharVenda.setEnabled(false);
        btFecharVenda.setName("btFecharVenda"); // NOI18N
        btFecharVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharVendaActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setName("btCancelar"); // NOI18N
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setText("Sair");
        btSair.setName("btSair"); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbCPF))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBuscar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbQuantidade))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btIncluir))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbValorT)
                .addGap(10, 10, 10)
                .addComponent(lbValorTotal))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btFecharVenda)
                .addGap(368, 368, 368)
                .addComponent(btCancelar)
                .addGap(323, 323, 323)
                .addComponent(btSair))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbCPF)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBuscar))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbQuantidade)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIncluir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btRemoverItem)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValorT)
                    .addComponent(lbValorTotal))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFecharVenda)
                    .addComponent(btCancelar)
                    .addComponent(btSair)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1156, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbNumeroVenda.setText(Integer.toString(venda.getNumero()));
        SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
        String data = fm.format(venda.getDataVenda());
        lbDataVenda.setText(data);
        tfCPF.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        cliente = FormPrincipal.bdcliente.buscarCliente(tfCPF.getText());
        if(cliente != null){
            lbNomeCliente.setText(cliente.getNome());
            lbEnderecoCompleto.setText(cliente.getEndereco().getLogradouro() + ", " + cliente.getEndereco().getComplemento());
            lbTelefone.setText(cliente.getTelefone());
            lbEmailContato.setText(cliente.getTelefone());
            btConfirmar.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "CPF não cadastrado!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarItemActionPerformed
        try{
            livro = FormPrincipal.bdlivro.buscarLivro(Integer.parseInt(tfCodigoLivro.getText()));
            if(livro != null){
                lbTitulo.setText(livro.getTitulo());
                lbEditora.setText(livro.getFornecedor());
                lbValorUnitario.setText(Float.toString(livro.getValorUnitario()));
            }else{
                JOptionPane.showMessageDialog(null, "Código não encontrado!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Informe um código!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarItemActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja confirmar este cliente?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if(opcao == 0){
            venda.setCliente(cliente);
            btBuscar.setEnabled(false);
            tfCPF.setEnabled(false);
            tfCodigoLivro.setEnabled(true);
            btBuscarItem.setEnabled(true);
            tfQuantidade.setEnabled(true);
            btIncluir.setEnabled(true);
            btRemoverItem.setEnabled(true);
            btFecharVenda.setEnabled(true);
        }        
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        try{
            Item item = new Item();
            item.setLivro(livro);
            item.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
            item.calcularValorItem();
            venda.inserirItem(item);
            inserirTabela(livro, item);
            soma += item.getValorItem();
            lbValorTotal.setText("R$ " + soma);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Informe a quantidade!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btFecharVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharVendaActionPerformed
        if(venda.todosItens().size() > 0){
            int opcao = JOptionPane.showConfirmDialog(null, "Deseja fechar a venda?", "Atenção!", JOptionPane.YES_NO_OPTION);
            if(opcao == 0){
                FormPrincipal.bdvenda.adicionarVenda(venda);
                JOptionPane.showMessageDialog(null, "Venda fechada com sucesso!", "Finalizado!", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Adicione pelo menos um item para fechar a compra!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btFecharVendaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverItemActionPerformed
        try{
            int linha = tbLivros.getSelectedRow();
            int codigo = (Integer) tbLivros.getModel().getValueAt(linha, 0);
            float valor = (Float) tbLivros.getModel().getValueAt(linha, 4);
            soma -= valor;
            lbValorTotal.setText(Float.toString(soma));
            venda.removerItem(codigo);
            modelo.removeRow(linha);
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Não há itens para remover!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRemoverItemActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        venda = new Venda();
        formularioInicial();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void limparTabela(){
        for(int i = tbLivros.getRowCount()-1; i >= 0; i--){
            modelo.removeRow(i);
        }
    }
    
    private void inserirTabela(Livro livro, Item item){
        modelo.addRow(new Object[]{livro.getCodigo(), livro.getTitulo(), item.getQuantidade(), 
        livro.getValorUnitario(), item.getValorItem()});
    }
    
    private String formataData(Venda venda){
        SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
        String data = fm.format(venda.getDataVenda());
        return data;
    }
    
    private void formularioInicial(){
        tfCPF.setEnabled(true);
        btBuscar.setEnabled(true);
        btConfirmar.setEnabled(false);
        tfCodigoLivro.setEnabled(false);
        btBuscarItem.setEnabled(false);
        tfQuantidade.setEnabled(false);
        btIncluir.setEnabled(false);
        btRemoverItem.setEnabled(false);
        btFecharVenda.setEnabled(false);
        lbValorTotal.setText("R$ 0.00");
        soma = 0;
        limparTabela();
        lbNumeroVenda.setText(Integer.toString(venda.getNumero()));        
        lbDataVenda.setText(formataData(venda));
        tfCPF.requestFocus(); 
        tfCPF.setValue("");
        lbNomeCliente.setText("");
        lbEnderecoCompleto.setText("");
        lbTelefone.setText("");
        lbEmailContato.setText("");
        lbTitulo.setText("");
        lbEditora.setText("");
        lbValorUnitario.setText("");
        tfCodigoLivro.setText("");
        tfQuantidade.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscarItem;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btFecharVenda;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btRemoverItem;
    private javax.swing.JButton btSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDataVenda;
    private javax.swing.JLabel lbEd;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailContato;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEnderecoCompleto;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbNumeroVenda;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTi;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValorT;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JLabel lbValorUnitario;
    private javax.swing.JLabel lbVenda;
    private javax.swing.JTable tbLivros;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfCodigoLivro;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
