/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.Component;
import java.util.Enumeration;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import model.Cliente;
import model.Endereco;

/**
 *
 * @author Luís Gustavo
 */
public class FormCliente extends javax.swing.JFrame {
    
    public FormCliente() {
        initComponents();
        btBuscar.setBackground(Color.white);
        btCadastrar.setBackground(Color.white);
        btAtualizar.setBackground(Color.white);
        btLimpar.setBackground(Color.white);
        btSair.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grEstadoCivil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbCPF = new javax.swing.JLabel();
        tfCPF = new javax.swing.JFormattedTextField();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDados = new javax.swing.JPanel();
        lbTelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jpEstadoCivil = new javax.swing.JPanel();
        rbSolteiro = new javax.swing.JRadioButton();
        rbCasado = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbEstavel = new javax.swing.JRadioButton();
        rbViuvo = new javax.swing.JRadioButton();
        jpEndereco = new javax.swing.JPanel();
        lbLogradouro = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lbCEP = new javax.swing.JLabel();
        tfCEP = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setPreferredSize(new java.awt.Dimension(680, 386));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCPF.setText("CPF:");
        lbCPF.setName("lbCPF"); // NOI18N

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF.setName("tfCPF"); // NOI18N
        tfCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCPFMouseExited(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNome.setText("Nome Completo:");
        lbNome.setName("lbNome"); // NOI18N

        tfNome.setName("tfNome"); // NOI18N
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomeKeyTyped(evt);
            }
        });

        btBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/buscar.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setName("btBuscar"); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/inserirCliente.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.setName("btCadastrar"); // NOI18N
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.setName("btAtualizar"); // NOI18N
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setName("btLimpar"); // NOI18N
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setName("btSair"); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(214, 217, 223));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setName("jpDados"); // NOI18N

        jpDados.setBackground(new java.awt.Color(214, 217, 223));

        lbTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTelefone.setText("Telefone:");
        lbTelefone.setName("lbTelefone"); // NOI18N

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setName("tfTelefone"); // NOI18N
        tfTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefoneMouseExited(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEmail.setText("Email:");
        lbEmail.setName("lbEmail"); // NOI18N

        tfEmail.setName("tfEmail"); // NOI18N

        jpEstadoCivil.setBackground(new java.awt.Color(214, 217, 223));
        jpEstadoCivil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estado Civil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpEstadoCivil.setName("jpEstadoCivil"); // NOI18N

        rbSolteiro.setBackground(new java.awt.Color(214, 217, 223));
        grEstadoCivil.add(rbSolteiro);
        rbSolteiro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSolteiro.setSelected(true);
        rbSolteiro.setText("Solteiro");
        rbSolteiro.setName("rbSolteiro"); // NOI18N

        rbCasado.setBackground(new java.awt.Color(214, 217, 223));
        grEstadoCivil.add(rbCasado);
        rbCasado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbCasado.setText("Casado");
        rbCasado.setName("rbCasado"); // NOI18N

        rbDivorciado.setBackground(new java.awt.Color(214, 217, 223));
        grEstadoCivil.add(rbDivorciado);
        rbDivorciado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbDivorciado.setText("Divorciado");
        rbDivorciado.setName("rbDivorciado"); // NOI18N

        rbEstavel.setBackground(new java.awt.Color(214, 217, 223));
        grEstadoCivil.add(rbEstavel);
        rbEstavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbEstavel.setText("União Estável");
        rbEstavel.setName("rbEstavel"); // NOI18N

        rbViuvo.setBackground(new java.awt.Color(214, 217, 223));
        grEstadoCivil.add(rbViuvo);
        rbViuvo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbViuvo.setText("Viúvo");
        rbViuvo.setName("rbViuvo"); // NOI18N

        javax.swing.GroupLayout jpEstadoCivilLayout = new javax.swing.GroupLayout(jpEstadoCivil);
        jpEstadoCivil.setLayout(jpEstadoCivilLayout);
        jpEstadoCivilLayout.setHorizontalGroup(
            jpEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstadoCivilLayout.createSequentialGroup()
                .addComponent(rbSolteiro)
                .addGap(53, 53, 53)
                .addComponent(rbCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(rbDivorciado)
                .addGap(56, 56, 56)
                .addComponent(rbEstavel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(rbViuvo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpEstadoCivilLayout.setVerticalGroup(
            jpEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstadoCivilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSolteiro)
                    .addComponent(rbCasado)
                    .addComponent(rbDivorciado)
                    .addComponent(rbEstavel)
                    .addComponent(rbViuvo))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(115, 115, 115))
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Pessoais", jpDados);

        jpEndereco.setBackground(new java.awt.Color(214, 217, 223));

        lbLogradouro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLogradouro.setText("Logradouro:");
        lbLogradouro.setName("lbLogradouro"); // NOI18N

        tfLogradouro.setName("tfLogradouro"); // NOI18N

        lbComplemento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbComplemento.setText("Complemento:");
        lbComplemento.setName("lbComplemento"); // NOI18N

        tfComplemento.setName("tfComplemento"); // NOI18N

        lbCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCidade.setText("Cidade:");
        lbCidade.setName("lbCidade"); // NOI18N

        tfCidade.setName("tfCidade"); // NOI18N

        lbEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEstado.setText("Estado:");
        lbEstado.setName("lbEstado"); // NOI18N

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.setName("cbEstado"); // NOI18N

        lbCEP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCEP.setText("CEP:");
        lbCEP.setName("lbCEP"); // NOI18N

        try {
            tfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCEP.setName("tfCEP"); // NOI18N
        tfCEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCEPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpEnderecoLayout = new javax.swing.GroupLayout(jpEndereco);
        jpEndereco.setLayout(jpEnderecoLayout);
        jpEnderecoLayout.setHorizontalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLogradouro)
                            .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbComplemento)
                            .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpEnderecoLayout.createSequentialGroup()
                                    .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEstado))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbCEP)))))
                        .addGap(38, 38, 38))
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addComponent(lbCidade)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpEnderecoLayout.setVerticalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(lbComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbEstado)
                    .addComponent(lbCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Endereço Completo", jpEndereco);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btCadastrar)
                        .addGap(71, 71, 71)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCPF)
                                .addGap(134, 134, 134)
                                .addComponent(lbNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lbCPF))
                            .addComponent(lbNome))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(697, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Cliente cliente = FormPrincipal.bdcliente.buscarCliente(tfCPF.getText());
        if(cliente == null){ 
            cliente = new Cliente();
            cliente.setCpf(tfCPF.getText());
            cliente.setNome(tfNome.getText());
            cliente.setTelefone(tfTelefone.getText());
            cliente.setEmail(tfEmail.getText());
            JRadioButton radio;
            String str;
            Enumeration jr = grEstadoCivil.getElements();
            while (jr.hasMoreElements()) {
                radio = (JRadioButton) jr.nextElement();
                if (radio.isSelected()) {
                    cliente.setEstadoCivil(radio.getText());
                }
            }
            cliente.getEndereco().setLogradouro(tfLogradouro.getText());
            cliente.getEndereco().setComplemento(tfComplemento.getText());
            cliente.getEndereco().setCidade(tfCidade.getText());
            cliente.getEndereco().setCep(tfCEP.getText());
            cliente.getEndereco().setEstado(cbEstado.getSelectedItem().toString());
            // Coloquei cada dado no cliente
            if(cliente.validaCliente()){
                FormPrincipal.bdcliente.inserirCliente(cliente);
                btAtualizar.setEnabled(true);
                tfCPF.setEnabled(false);
                btBuscar.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!", "Informação de Cadastro", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Atenção! Preencha todos os campos para cadastrar!", "Informações de Cadastro", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Atenção! Já existe cliente cadastrado com este CPF!", "Informação de Cadastro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        btAtualizar.setEnabled(false);
        String cpf = tfCPF.getText(); 
        String cpfSemMascara = cpf.replace(".", "").replace("-", "");
        if(!cpfSemMascara.trim().equals(""))
        {
            Cliente cliente = FormPrincipal.bdcliente.buscarCliente(cpf);
            if(cliente != null)
            {
                tfNome.setText(cliente.getNome());
                tfTelefone.setText(cliente.getTelefone());
                tfEmail.setText(cliente.getEmail());
                JRadioButton radio; 
                Enumeration jr = grEstadoCivil.getElements(); 
                while ( jr.hasMoreElements() ) { 
                    radio = (JRadioButton) jr.nextElement(); 
                    if (radio.getText().equals(cliente.getEstadoCivil())) 
                        radio.setSelected(true); 
                }
                tfLogradouro.setText(cliente.getEndereco().getLogradouro());
                tfComplemento.setText(cliente.getEndereco().getComplemento());
                tfCidade.setText(cliente.getEndereco().getCidade());
                tfCEP.setText(cliente.getEndereco().getCep());
                cbEstado.setSelectedItem(cliente.getEndereco().getEstado());
                btAtualizar.setEnabled(true);
                tfCPF.setEnabled(false);
                btBuscar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!", "Informação de Cadastro", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Informe o CPF para fazer a busca!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfCPF.setEnabled(true);
        btBuscar.setEnabled(true);
        for(int i = 0; i < getContentPane().getComponentCount(); i++)
        {
            Component c = getContentPane().getComponent(i); 
            if ( c instanceof JPanel)
            {
                JPanel p = (JPanel)c;
                for(int j = 0; j < p.getComponentCount(); j++)
                {
                    Component c2 = p.getComponent(j);
                    if (c2 instanceof JTabbedPane)
                    {
                        JTabbedPane p2 = (JTabbedPane)c2; 
                        for(int k = 0; k < p2.getComponentCount(); k++)
                        {
                            Component c3 = p2.getComponent(k);
                            if (c3 instanceof JPanel)
                            {
                                JPanel p3 = (JPanel)c3;
                                for(int l = 0; l < p3.getComponentCount(); l++)
                                {
                                    Component c4 = p3.getComponent(l);
                                    if (c4 instanceof JTextField)
                                    {
                                        JTextField field = (JTextField)c4; 
                                        field.setText("");
                                    }
                                    if (c4 instanceof JFormattedTextField)
                                    {
                                        JFormattedTextField field = (JFormattedTextField)c4; 
                                        field.setValue(null);
                                    }
                                }
                            }
                        }
                    }
                    if (c2 instanceof JTextField)
                    {
                        JTextField field = (JTextField)c2; 
                        field.setText("");
                    }
                    if (c2 instanceof JFormattedTextField)
                    {
                        JFormattedTextField field = (JFormattedTextField)c2; 
                        field.setValue(null);
                    }
                }
            }
        }
        
        grEstadoCivil.clearSelection();
        cbEstado.setSelectedIndex(0);
        btAtualizar.setEnabled(false);
        tfCPF.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void tfCPFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFMouseExited
        String cpfSemMascara = tfCPF.getText().replace(".", "").replace("-", "");
        if(cpfSemMascara.trim().equals(""))
        {
            tfCPF.setValue(null);
        }
    }//GEN-LAST:event_tfCPFMouseExited

    private void tfTelefoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneMouseExited
        String telefoneSemMascara = tfTelefone.getText().replace("(", "").replace(")", "").replace("-", "");
        if(telefoneSemMascara.trim().equals(""))
        {
            tfTelefone.setValue(null);
        }
    }//GEN-LAST:event_tfTelefoneMouseExited

    private void tfCEPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCEPMouseExited
        String cepSemMascara = tfCEP.getText().replace("-", "");
        if(cepSemMascara.trim().equals(""))
        {
            tfCEP.setValue(null);
        }
    }//GEN-LAST:event_tfCEPMouseExited

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        Cliente cli = FormPrincipal.bdcliente.buscarCliente(tfCPF.getText());
        if(cli != null)
        {
            int recebe = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar os dados?", "Atenção", JOptionPane.YES_NO_OPTION);
            if(recebe == 0)
            {
                Cliente cliente = new Cliente();
                JRadioButton radio; 
                String estadoCivil = null;
                Enumeration jr = grEstadoCivil.getElements(); 
                while ( jr.hasMoreElements() )
                {
                    radio = (JRadioButton) jr.nextElement(); 
                    if (radio.isSelected())
                    {
                        estadoCivil = radio.getText();
                    }
                }
                cliente.setCpf(tfCPF.getText());
                cliente.setNome(tfNome.getText());
                cliente.setTelefone(tfTelefone.getText());
                cliente.setEmail(tfEmail.getText());
                cliente.setEstadoCivil(estadoCivil);

                Endereco endereco = new Endereco();
                endereco.setLogradouro(tfLogradouro.getText());
                endereco.setComplemento(tfComplemento.getText());
                endereco.setCidade(tfCidade.getText());
                endereco.setCep(tfCEP.getText());
                endereco.setEstado(cbEstado.getSelectedItem().toString());
                cliente.setEndereco(endereco);
                FormPrincipal.bdcliente.atualizarCliente(cliente);
                JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!", "Informação de Atualização", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Você alterou o CPF!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void tfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyTyped
        String caracteres = "0987654321";
        if(caracteres.contains(evt.getKeyChar() + ""))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.ButtonGroup grEstadoCivil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpEndereco;
    private javax.swing.JPanel jpEstadoCivil;
    private javax.swing.JLabel lbCEP;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbEstavel;
    private javax.swing.JRadioButton rbSolteiro;
    private javax.swing.JRadioButton rbViuvo;
    private javax.swing.JFormattedTextField tfCEP;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
